language: python
python:
  - "3.8"
before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    sudo apt-get update
    sudo apt-get install --yes libpoppler-cpp-dev pkg-config
    fi
install:
  - pip install -r requirements.txt
  - pip install git+https://github.com/rafelafrance/traiter.git@master#egg=traiter
script:
  - python -m unittest discover
