# Regular expressions for stripping lines and sections from
# the text document.
[regex]
acknowledge  = '^Acknowledgments$'
advance_acc  = '^Advance Access'
all_rights   = '^All rights reserved'
authors      = '^The Authors'
doi          = '^doi'
fig_heading  = '^Fig'
journal_of   = '^Journal of'
keywords     = '^Key\s?words'
line_no      = '^\d+$'
research_art = '^Research article'
single_char  = '^[A-Za-z]$'
version_of   = '^Version of Record'


# A character translation table to handle custom mojibake.
# The ftfy library handles common mojibake.
[trans]
equals = ['¼', '=']
times  = ['⫻', '×']
female = ['#', '♂']
male   = ['$', '♀']


[Medical_Entomology]
mojibake = [                            # Translate uncommon mojibake
    '@trans.equals',
    '@trans.times',
    '@trans.female',
    '@trans.male',
]
remove_before = ['@regex.keywords']     # Remove all lines before this
remove_after  = ['@regex.acknowledge']  # Remove all lines after this
remove_lines  = [                       # Remove all lines matching these patterns
    '@regex.journal_of',
    '@regex.fig_heading',
    '@regex.single_char',
    '@regex.authors',
    '@regex.all_rights',
    '@regex.version_of',
    '@regex.line_no',
    '@regex.doi',
    '@regex.advance_acc',
    '@regex.acknowledge',
    '@regex.keywords',
    '@regex.research_art',
]
